version: '3'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: imarket_development
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  web:
    image: tynmarket/table-viewer
    environment:
      DB_USER: root
      DB_NAME: imarket_development
      DB_HOST: db
      AUTH_USER: # Need to set.
      AUTH_PASSWORD: # Need to set.
    ports:
      - "80:80"
    depends_on:
      - db
    tty: true
    stdin_open: true

volumes:
  mysql_data:
