openapi: 3.0.0
info:
  title: select query
  version: '1.0'
  description: Select query endpoint for table-viewer
  contact:
    name: tynmarket
    email: tynmarket@gmail.com
    url: 'https://tyn-imarket.com/'
servers:
  - url: 'http://localhost:3000/v1'
paths:
  /select:
    post:
      summary: Your POST endpoint
      tags:
        - query
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      hader:
                        type: array
                        items:
                          type: string
                      records:
                        type: array
                        items:
                          $ref: '#/components/schemas/Record'
              examples:
                response:
                  value:
                    data:
                      header:
                        - id
                        - code
                        - name
                      records:
                        - - 1
                          - '4368'
                          - 扶桑化学
                        - - 2
                          - '9985'
                          - ソフトバンク
      operationId: get-select
      description: 対象のテーブルに対してSELECTクエリを実行した結果を取得する
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                table:
                  type: string
                where:
                  type: array
                  items:
                    $ref: '#/components/schemas/WhereQuery'
                order:
                  type: string
              required:
                - table
            examples:
              body:
                value:
                  table: disclosures
                  where:
                    - column: id
                      operator: '>'
                      value: '1'
                  order: DESC
        description: ''
components:
  schemas:
    WhereQuery:
      title: WhereQuery
      type: object
      properties:
        column:
          type: string
        operator:
          type: string
        value:
          type: string
      required:
        - column
        - operator
    Record:
      title: Record
      type: array
      items:
        anyOf:
          - type: string
          - type: number
          - type: boolean
  securitySchemes: {}
tags:
  - name: query
    description: SQLのクエリ
